PyFstat/PyFstat

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- tests.py
-fixes #13
I've added the new input variables to ComputeFstat and all derived classes in core.py, grid_based_searches.py and mcmc_based_searches.py. But I'm somewhat confused about the different ways they do their inits, some explicitly setting self.xxx=xxx and some not, etc. So this might not all be sane, even though tests seem to all pass, but I know we don't have full coverage.
I should also add at least one test that explicitly uses the manual options.
> add manual ephemerides options to search classes

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- pyfstat/mcmc_based_searches.py
- tests.py
Found this old branch lying around. I think I started this in the suspicion that it would fix some weird failures with ephemerides finding on a non-standard platform, which turned out to have another source in the end. But it's still a good idea for portability. So if black is ok with it, we should merge it in.
> use os.path.join instead of manual string joining with "/"

- pyfstat/helper_functions.py
Suppress messages from get_version_information():
```
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
> helper_functions.get_version_information: suppress git error messages

- examples/followup_examples/semi_coherent_directed_follow_up.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
As per #7 this adds simple ASCII export of MCMC samples. Passes the tests and looks sane in the first few example cases, but I will check how it works on a real-life follow-up example before merging.
Uses the same file header as GridSearch.
> MCMC: export samples to ASCII file

- examples/followup_examples/semi_coherent_directed_follow_up.py
- pyfstat/mcmc_based_searches.py
- tests.py
@Rodrigo-Tenorio This should solve the problem in #32 that you had previously spotted when re-running the `examples/followup_examples/semi_coherent_directed_follow_up.py` case.
I decided to do a **backwards-incompatible** change to the arguments of both `MCMCFollowUpSearch.run()` and `MCMCSearch.run()`:
- rename `create_plots` option to `plot_walkers` for clarity
- replace `kwargs` pass-through to `_plot_walkers()` with explicit `walker_plot_args` dictionary
- in `MCMCFollowUpSearch.run()` don't return `fig`, `axes` but store as `self.walker_fig`, `self.walker_axes`
- introduce the same feature to the base `MCMCSearch.run()`
- adapt the followup example script to explicitly check if fig and axes were stored; if not, it's likely because old data was used, and it won't overwrite the figure. …
> MCMC: improve handling of walker plots

- pyfstat/mcmc_based_searches.py
1. use the actual max2F point instead of the median to do the extra CFSv2 run
1. pass --refTime
see #43
> fixes to MCMSearch.generate_loudest()

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
As a solution to #35, actually I think this is better than #45. Not a separate dump file, but adding the parameter dict to the existing header of each output file. Similar to the lalapps convention.
@GregoryAshton @ReinhardPrix @Rodrigo-Tenorio how does this look?
example output from the fully_coherent_search_using_MCMC.py example:
```
30.00000000356636 -1.00003001670372e-10
[...]
```
> output file headers: include search class name and init arguments dict

- setup.py
Until we can figure out *why* the new 6.71 causes the weird
```
INTERNALERROR> TypeError: not a code object: <class 'pyfstat.make_sfts.Writer'>
```
on all pipelines (#52), this seems to do the trick.
> pin lalsuite==6.70 to fix github pipelines

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
This will make the transient examples run through again, which first failed due to a `_set_init_params_dict()` call I had forgotten, but from that failure's output I luckily also noticed that CFSv2 errors in `MCMCSearch.generate_loudest()` were not actually caught by the subprocess call, and then I had to fix a bunch more commandline options in that call.
The examples will still produce inconsistent max2F values, which will need to be fixed next -> #54
> Fix transient searches

- requirements.txt
- setup.py
Let's also require `lalsuite>=6.72` so nobody runs into "not a code object" from 6.71 again.
> sync requirements.txt and setup.py

- pyfstat/make_sfts.py
- tests.py
As pointed out by @Rodrigo-Tenorio in #50, the Writer default of `sqrtSX=1` is odd, and particularly dangerous now that we also allow for noiseSFTs. Historically it was probably introduced to match the `assumeSqrtSX=1` default of the F-stat codes (Compute & Predict), but as far as I can see that isn't really necessary, as one can always manually set `assumeSqrtSX=1` for those even if the SFTs actually contain 0 noise.
This PR:
-  changes the Writer default
-  adapts the warning message introduced in #41
-  adds the missing feature for setting assumeSqrtSX when wanting to predict F directly from the Writer
-  improves the test suite
In particular, the only test failing after the first commit was `test_get_semicoherent_twoF`, because it picked up spurious SFTs from the other test case in …
> Writer: default to sqrtSX=0

- .github/workflows/docker-publish.yml
- Dockerfile
- README.md
Build a Docker container using Python 3.8 and the last commit in master branch.
Containers can be pulled using Docker/Singularity, requiring a Personal Access Token with "read:packages" privileges.
This is a nice-to-have feature, since allows PyFstat to be used out of the box in almost every feasible situation* without any painful dependency drama.
*Provided Singularity is available, which is sort of a current trend
> Add docker workflow

- pyfstat/core.py
Encountered this while accidentally running python 2.7 which we no longer support, but best to fix encoding issues anyway since they may cause whatever later.
> core.py: fix "SyntaxError: Non-ASCII character '\xc3'"

- pyfstat/mcmc_based_searches.py
resolves #61 by changing this only direct `subprocess` call to use the central `run_commandline()` helper function.
> MCMCSearch.generate_loudest(): change to use run_commandline()

- .github/workflows/docker-publish.yml
checkout@v2 only picks up the last commit by default [see the official docs](https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches). Add the suitable argument to the action file and #76 is done!
> docker build: Fetch all history using checkout@v2

- pyfstat/mcmc_based_searches.py
Since a proper `CFSv2 --outputLoudest` functionality for the transient max2F statistic (instead of regular CW 2F) would require changes to that code itself in lalapps, for now I'll "resolve" #54 simply by adding a warning.
> MCMCSearch.generate_loudest(): warn for transients

- .github/workflows/integration.yml
First to TestPyPI, then the real one, with same logic (only on tagged releases and only for newest python version).
> publish releases to real PyPI

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
Another big-ish change. A while ago in a9e993dddae9424d4f01d3f24d42435228e348e8 I introduced the possibility to call an XLAL function to estimate the "covering band" to actually grab from the given SFTs. This is essential in being able to 1:1 reproduce results from CFSv2, and also should be more robust and general than the previous practice of estimating as `[min(SFTs)+0.5,max(SFTs)-0.5]` if the user didn't give manual options.
New behaviour now:
- use `estimate_min_max_CoverFreq()` by default,  based on search ranges (grid boundaries for grid searches / prior bounds for MCMC searches)
- deprecate `estimate_covering_band` user-facing option (has only been live for a month, so shouldn't break too much)
- old behaviour of SFT ranges +- 0.5 can now be reproduced by passing negative …
> Estimate coverage bands by default, extend feature to binaries

- pyfstat/core.py
Semicoherent Fstat is computed using LALSuite's TransientFstatMap (there's no native implementation otherwise!); such implementation was properly documented in [the paper](https://arxiv.org/abs/1802.05450) through a characteristic time tau_T ~ 1.5e-8 (s), which conforms the main time contribution for all our purposes (i.e. Nsft ~ O(1e3 - 1e4) and Nsegments ~ O(1e2 - 1e3) ).
This PR improves tau_T by a factor of ~5 (tau_T ~ 2.8e-9 s) introducing the following changes:
- Given *nsegs* segments, we set up *nsegs* rectangular transient windows and call  `lalpulsar.ComputeTransientFstatMap` **once** (previous approach used *one* rectangular window and called the function *nsegs* times).
- We introduce a new variable `self._semicoherent_window_trick` to carry the transient window around, …
> Call computetransientfstatmap once

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- tests.py
Following up from #98:
-should be computed from summed F-stats,
not per segment and then summed itself
-also fixed method names:
get_semicoherent_twoF -> get_semicoherent_det_stat
_get_per_segment_det_stat -> _get_per_segment_twoF
-and made this one into a proper loop over arbitrary numDet,
though rest of package doesn't fully support >2 yet
> fix semicoherent BSGL

- examples/mcmc_vs_grid_simple_example/PyFstat_example_make_data_for_simple_mcmc_vs_grid.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_plot_grid_vs_mcmc_comparison.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_grid_search.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_search.py
@Rodrigo-Tenorio here's the comparison examples I mentioned, but apparently never committed.
Taking the basic signal parameters from one of the transient examples. 2 days of data, depth 10, MCMC priors are a uniform box exactly covering the same range as the grid. This runs super fast and produces very consistent outputs:
grid:
```
Grid point with max(twoF) for grid_search:
minStartTime=1000000000.0
maxStartTime=1000172800.0
F0=29.999997578534796
F1=-7.286372986119523e-11
F2=0.0
Alpha=0.5
Delta=1.0
twoF=227.90359497070312
```
MCMC:
```
13:51 INFO    : Plotting temperature 0 chains
13:51 INFO    : Summary:
13:51 INFO    : Max twoF: 227.98948669433594 with parameters:
F0         = 2.999999759e+01
F1         = -7.228125065e-11
13:51 INFO    : Median +/- std for production values
13:51 INFO …
```
> add mcmc_vs_grid_simple_example

- pyfstat/core.py
- pyfstat/mcmc_based_searches.py
- tests.py
First commit splits the MCMCSearch test case into two: 
- test_fully_coherent_MCMC_fixedsky
- test_fully_coherent_MCMC_skyprior
- the latter exposes bug from https://github.com/PyFstat/PyFstat/issues/106
@Rodrigo-Tenorio will look into a fix
> expose and fix bug in estimate_min_max_CoverFreq for non-fixed sky locations

- pyfstat/core.py
- tests.py
It seems that in #98 we introduced an error in the setup of the "window range" used for the semicoherent sum trick.
For N segments, we need to go N steps of length Tcoh each from Tstart to Tend-Tcoh, not only to Tend-2*Tcoh.
The first commit exposes this in the tests by explicitly checking the length of `search.twoF_per_segment` (error wasn't caught before because the computation and checking of relative errors doesn't mind if comparing length 1 against length 2). The second fixes it.
@Rodrigo-Tenorio please confirm there was no deeper reason for the factor 2 in the t0Band. I suspect you may have followed transient code somewhere where it has to make sure to only go to `Tend-2*Tsft`, because the Demod F-stat implementation deep down requires Nsft>=2 and hence otherwise the last window …
> SemiCoherentSearch: fix off-by-one error in segments setup

- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
This resolves #97.
- So far, I've taught the `MCMCSearch::test_fully_coherent_MCMC` test case to loop over multiple prior choices -- this could be much more elegantly done with `@pytest.mark.parametrize` but that cannot be mixed with unittest classes which is our standard approach otherwise. Porting the whole test suite to pure `pytest` would be another 2.0 wishlist feature.
- Fixed various issues for some of the more exotic prior types, including most significantly that the `lognorm` type was only implemented in some methods but not everywhere. It's an odd one because the standard parametrizations of scipy and numpy don't match too well, but as demonstrated by the attached separate [test script](https://github.com/PyFstat/PyFstat/files/5030324/test_numpy_scipy_lognorm.py.txt) and plots I …
> add more MCMC tests, fix some prior types

- tests.py
To get around #112 until I get a proper solution up.
> tests: temporarily disable MCMC parameter accuracy checks

- pyfstat/make_sfts.py
- tests.py
Solve #84 by splitting the input data handling in two cases depending on whether `noiseSFTs` was given or not.
If the former, use `lalpulsar` tools to infer as much information from them as possible; if the latter, do what's been always done.
I'll have to think about how to deal with `tstart` and so on: I could ignore them if `noiseSFTs` are give, or change the default value to some `None` in order to prevent them from being used/confused (although that would probably imply dealing with the test suite and the infamous #71)
> make_sfts.py/Split setup depending on noiseSFTs

- pyfstat/make_sfts.py
@Rodrigo-Tenorio  this was ":1.18e" as for Doppler parameters,  which apparently trips lalpulsar up
and makes it extrapolate to nonsense frequencies. This made some changes I'm working on with automatic `--Band` estimation fail in very confusing ways, but best to merge it in first separately. Let's see if the master version of the test suite likes it...
> BinaryModulatedWriter: fix refTime format in .cff

- pyfstat/make_sfts.py
- tests.py
After #83, `noiseSFTs` are handled in a proper way (meaning things like #82 are  trivial to fix/modify since they are practically a method on their own.
This PR simply ensures that data with gaps (or non-contiguous data) is properly handled both by MFD and PyFstat (which needs to set the proper `sftfilepath` by counting the number of SFTs).
> tests.py/Include test case using data with gaps

- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- tests.py
Still need to fix some of the tests, but this makes it so that, as per the doc string:
```
Band: float or None
If float, output SFTs cover [F0-Band/2,F0+Band/2].
If None, a minimal covering band for a perfectly-matched
single-template ComputeFstat analysis is estimated.
```
> Writer: auto-estimate Band if None

- pyfstat/make_sfts.py
- tests.py
Refs #90. ~~To be applied after #121 (only the last commit is new).~~
- this was on by default and not adding any functionality besides switching off sqrtSX and/or noiseSFTs
- old add_noise=False behaviour can be obtained with just leaving noiseSFTs=None and sqrtSX=None (or sqrtSX=0)
- also change default for sqrtSX to None as MFDv5 has an internal default of 0 anyway
- fix and further clean up some of the tests
> Writer: remove add_noise option

- pyfstat/make_sfts.py
- This functionality is already allowed by the ComputeFstat branch
of BaseSearchClass' childs.
- No major changes, only the option to give them manually if one
so desires.
> make_sfts.py/Include ephemeris as input argument

- examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
- examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
- examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_make_data_for_simple_mcmc_vs_grid.py
- examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
- examples/other_examples/PyFstat_example_sliding_window.py
After #125 #122 and #121 examples are likely to be broken due to some backwards incompatible changes in the default arguments.
Refer to #123 for a brief summary (i.e. sanity check) of examples' outputs.
> Make examples compatible again

- pyfstat/__init__.py
- pyfstat/core.py
- pyfstat/make_sfts.py
- tests.py
- move special methods for glitch / timing noise cases
from BaseSearchClass to this
- SemiCoherentGlitchSearch and GlitchWriter now inherit from new class
- adapt tests
@GregoryAshton to be honest I always found these special methods a bit distracting right at the top of `BaseSearchClass`, and having them hidden away further down will also make life a bit easier with reviewers. ;) Is this ok with you? (Superficial look at the idea of the change is sufficient.) We don't really have very good test coverage for the glitch-robust functionality, but at least the basic tests that exist still pass.
@Rodrigo-Tenorio You seem to understand inheritance better than me, any problems you can see with the two parents for SemiCoherentGlitchSearch and GlitchWriter?
PS: The alternative to dual inheritance …
> new class SearchForSignalWithJumps

- examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
- pyfstat/mcmc_based_searches.py
Work in #134 
- A *single* point can be added through the "truths" parameters (this is
due to the way corner is coded).
- If it's a list of values, plot straight.
- If it's a dictionary, get a list from it.
> Add options to plot injection parameters for diagnosis

- examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
- pyfstat/make_sfts.py
`tp` suffers from the same problem as `tref` in #120 . This makes sense, as both of them [are parsed using the same function in MFD](https://lscsoft.docs.ligo.org/lalsuite/lal/_config_file_test_8c_source.html).
I'll check the rest of parsing functions to make sure nothing else is broken.
> Fix periastron time format

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- pyfstat/mcmc_based_searches.py
- tests.py
- some minor help/logging improvements
- remove the various options/methods deprecated in the 1.5.x series.
- more significant cleanup of core module:
- remove Bunch class which wasn't used except for an isolated test case
- turn translate_keys_to_lal() into a BaseSearchClass method
- move read_par() to helper_functions but also add a BaseSearchClass method
- simplify read_par() by always returning a regular dict
- move predict_fstat() from core to helper_functions
> cleanup: remove Bunch class, refactor some functions, remove deprecated options

- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- requirements.txt
- setup.py
- tests.py
- since lalapps 6.26.1, PFS option combinations have changed a bit
including new --duration when *not* using --DataFiles
- now wrap the various combinations, making most arguments optional,
in helper_functions.predict_fstat()
- using maxStartTime=minStartTime+duration in with-DataFiles case
is safe here following the usual [,) convention
- but keep the original mode in Writer.predict_fstat():
always use sftfilepattern, since (tstart,duration) do not
fully prescribe the actual data set if we started from
noiseSFTs with gaps
- also improved documentation of helper_functions.predict_fstat()
- closes  #132
@Rodrigo-Tenorio for review, but not very urgent.
PS: Forgot the most important bit: will bump lalsuite dependency to >= 6.76.
> predict_fstat updates and require lalsuite >= 6.76

- .github/workflows/integration.yml
- README.md
- examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
- examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
- examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
- examples/grid_examples/PyFstat_example_grid_search_F0.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_grid_search.py
- examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
- examples/run_all_examples.py
- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- pyfstat/mcmc_based_searches.py
- pyfstat/tcw_fstat_map_funcs.py
- setup.cfg
- tests.py
We've had `flake8` config settings in `setup.cfg` for a while since `black` also uses them, but we have not actually run this linter. Locally I get at the moment:
```
1     E266 too many leading '#' for block comment
1     E722 do not use bare 'except'
1     E731 do not assign a lambda expression, use a def
3     E741 ambiguous variable name 'l'
5     F401 'matplotlib.pyplot as plt' imported but unused
3     F811 redefinition of unused 'outdir' from line 5
28    F821 undefined name 'sampler'
5     F841 local variable 'e' is assigned to but never used
66    W605 invalid escape sequence '\m'
```
> adopt flake8 linting

- pyfstat/make_sfts.py
- need to loop over `self.sftfilepath.split(";")`
- also once again store MFD option `--IFOs` in quoted format matching its internal string-list handling (regression from 523454ee)
- improve check logic and logging output
- also fix method name `check_if_cff_file_needs_rewritting()` -> `check_if_cff_file_needs_rewriting()`
- closes #161
> Writer: fix check_cached_data_okay_to_use() for multiple IFOs

- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
The current version can lead to Frankenstein figures when doing custom plots in a wrapper script after calling some of the pre-implemented plotting methods.
- do this in various grid and MCMC search methods
- also add save_fig option to MCMCSearch.plot_prior_posterior()
There is still some horrible inconsistency in argument names and returns of these plotting methods, I'll open a separate reminder issue about those.
> close figures after saving (if not returning)

- pyfstat/core.py
- pyfstat/tcw_fstat_map_funcs.py
This solves part of #163 : Every single class will announce itself before doing any action.
Also cleans up inheritances from `object`, which are not needed anymore (welcome to Python3, PyFstat!)
> Include logging print after every instantiation

- examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
- examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
- examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
- examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
- pyfstat/mcmc_based_searches.py
Let's use this as a starting point to fix #166. So far only amends one example to expose the issue in the walker plot:
Not actually sure right now if corner plots are also affected, this one looks fine but I'd need to double-check other examples without my messy cahnges from #171.
> MCMC plots: properly rescale injection parameters

- pyfstat/make_sfts.py
- only say "Writing" after check for whether to do it
- and improve formatting
The output previously was confusing, like this:
```
16:17 INFO    : Writing the following injection parameters to config file TestData/test.cff:
16:17 INFO    : [TS0]
Alpha = 5.000000000000000104e-03
Delta = 1.199999999999999956e+00
h0 = 1.000000000000000000e+02
cosi = 0.000000000000000000e+00
psi = 0.000000000000000000e+00
transientWindowType = none
refTime = 700000000.000000000
Freq = 3.000000000000000000e+01
f1dot = -1.000000000000000036e-10
f2dot = 0.000000000000000000e+00
phi0 = 0.000000000000000000e+00
16:17 INFO    : Checking if we can re-use injection config file...
16:17 INFO    : ...no config file TestData/test.cff found.
```
> fix logging of Writer.make_cff()

- tests.py
I noticed that the `test_grid_search_against_CFSv2` was giving very low, noise-like 2F values. After changing it to the correct F1,F2,Alpha,Delta, now the peak is at 1.64757458e+03 - much nicer.
No actual change in test validity, just makes the output more meaningful if one goes into the tests and actually looks at them.
> tests of grid searches: use actual injection parameters in the non-gridded dimensions

- pyfstat/grid_based_searches.py
Another small fix for this function, for cases where differently-dimensioned input arrays are requested than what's stored in the rerefence file. That should normally already trip up the header consistency check, but not if internals have changed between runs.
- avoid np.allclose() below complaining
- only testing number of points, not number of dimensions, here
because output file can have detstat and post-proc quantities
added and hence have different number of dimensions
(this could in principle be cleverly predicted at this point,
but left for future work)
> GridSearch.check_old_data_is_okay_to_use(): add length check

- examples/binary_examples/PyFstat_example_binary_mcmc_vs_grid_comparison.py
There is no actual implementation of a Binary Grid Search, so I had to do it by hand.
It's obviously based in [this other example](https://github.com/PyFstat/PyFstat/blob/master/examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py).
> add mcmc vs grid binary comparison example

- pyfstat/grid_based_searches.py
- tests.py
For further discussion. This is to be more consistent in handling endpoint inclusion in grid arrays, but doesn't really solve 1:1 comparisons with CFSv2.
- previous `np.arange()` usage led to seemingly random inclusion or exclusion of the end point requested through the `[start,end,step]` format
- following numpy docs recommendation for non-integer stepsizes:
> "When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases."
- now this should always consistently include end point
- CFSv2 isn't a reliable target to match before or after, so change test case to a set of F0s that happens to match the new convention
@ReinhardPrix as a CFSv2 authority, I'm wondering if you have any opinion/advice on this?
My impression …
> GridSearch.get_array_from_tuple(): change from np.arange() to np.linspace()

- examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
Overly hacky manual choice exposed by #185.
Fixed version:
> fix plot_corner(truths) in glitch example

- pyfstat/helper_functions.py
- none are passed through to the commandline tool
- which would be very fragile anyway
- so all this enables is dangerous backwards fake-compatibility
as exposed in #186
> remove kwargs from helper_functions.predict_fstat()

- .github/workflows/integration.yml
- tests.py
Address #193 .
It won't go faster than this, as the rest of the time seems to be spent in set up commands. 
We should gain 30s and a `--durations=0` flag to keep an eye on what we do.
> Make tests faster

- examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
- examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
- examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
- examples/other_examples/PyFstat_example_twoF_cumulative.py
- pyfstat/core.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
Make #170 work again
And I guess @dbkeitel would like
More issues to deal with:
> Fix cumulative twoF

- .github/workflows/integration.yml
- .pre-commit-config.yaml
- README.md
- bin/check_if_virtual_environment.py
- bin/get-and-export-ephemeris.sh
- bin/get_and_export_ephemeris.sh
- bin/setup-dev-tools.sh
- requirements-dev.txt
Automates the set up of a development environment by just running a bash script.
The script:
- Makes sure one is developing inside a virtual environment.
- Installs `pytest`, `flake8`, `black` and `pre-commit`.
- Sets up pre-commit hooks to run `flake8` and `black`.
Optionally, we could add a script to authomatically download ephemeris (which will be only needed if installed from `pip`).
@dbkeitel Opinions?
> Setup dev environment

- pyfstat/core.py
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- pyfstat/mcmc_based_searches.py
Several classes/functions take sqrtSX-type inputs which can be single values or per-IFO lists, and their type can in principle be either a float, list of floats, list of strings or comma-separated string. These are then variously passed to lalapps commandlines (requiring simple floats or strings), passed to swig-wrapped lal functions (requiring lists) or checked PyFstat-internally for being > or < 0 (currently failing if a list or string).
We could somehow curb this chaos at the highest-level user-facing input stage by only accepting one format, but here's a semi-elegant attempt to be robust in parsing this.
One uncovered failure mode is if the user input is a list and a command-line gets constructed from it with plain `format`, but at least the error message from lalapps should be clear …
> improve sqrtSX handling

- pyfstat/make_sfts.py
- tests.py
I think this is sufficient to fix #202. The alternative `_get_setup_from_noiseSFTs()` case should be fine already, since there we are just taking the SFT file names as we've been given them, but I haven't dug explicitly into it.
> Fix expected SFT file names when duration is not multiple of Tsft

- tests.py
Uncouples Writer and signal parameters in order to add binary parameters through BinaryModulatedWriter through a class attribute. Fixes #190 .
> tests/Add BinaryModulatedWriter tests

- pyfstat/__init__.py
- pyfstat/make_sfts.py
- tests.py
Implement a class to generate injection parameters. 
The idea would be the same one one has been doing so far: Pick a rng and draw injection parameters from it. But, instead
of re-inventing the wheel every time, now we could just pass those arguments to this new class an query injection parameters on demand.
More desirable things:
- ~[ ] Make this class an iterable?~ Somehow I feel a callable makes more sense.
> Implement injection parameter generator

- pyfstat/core.py
- pyfstat/grid_based_searches.py
@Rodrigo-Tenorio This is the discussed implementation for the first step of #213.
cc @GregoryAshton @ReinhardPrix 
For future reference, step2, the usage of `DefunctClass` would look like:
```
class FrequencySlidingWindow(DefunctClass):
last_supported_version="1.8.0"
```
> Deprecate unmaintained grid classes

- tests.py
- finally I figured out why I always had some random SFTs in my root directory...
- leftover from some debugging obviously
> tests.py: remove spurious file copy

- examples/run_all_examples.py
- report each failed example on a single line
- use f-strings
- reduce vertical whitespace
> cleanup run_all_examples.py outputs

- README.md
Now recommend conda ahead of pip, remove some of the meta instructions (how to get conda) in favour of the (also updated [wiki page](https://github.com/PyFstat/PyFstat/wiki/conda-environments)), reshuffle the other sections a bit.
Closes #118/
> Readme: now available from conda forge, reshuffle sections

- .readthedocs.yml
The [first readthedocs builds off master](https://readthedocs.org/projects/pyfstat/builds/12655554/) actually didn't include the autodoc-generated contents as they failed to import dependencies. The web interface only allows to load in one `requirements.txt` file; let's see if through a yml we can use both the one in `docs` and the root-level one of PyFstat itself.
PS: as per https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file
> add .readthedocs.yml to allow using both requirements.txt files

- examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
- examples/grid_examples/PyFstat_example_grid_search_F0.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
- examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
- examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
This is another case where fixing something small ballooned into reworking a core feature, because working around it was just too messy.
The main change is to make `tstart` and `tend` optional arguments in the core function `get_fullycoherent_twoF()`, falling back to `self.minStartTime` and `self.maxStartTime` if they're `None`, which is sufficient for the basic CW classes `GridSearch` and `MCMCSearch` and only needs to be overridden point-by-point for some of the transient and glitch classes.
- requires lots of tracking changes in grid and mcmc searches
- change grid searches to use named-column ndarrays internally to avoid fragile numeric indexing
- partially clean up keys storage in MCMC searches
- change helper_functions.get_doppler_params_output_format() to return dict
- amend tests …
> make start, tend optional in get_fullycoherent_twoF()

- examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
- examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
- pyfstat/core.py
- pyfstat/mcmc_based_searches.py
- Fixes #228 (i.e. re-run safety of `MCMCGlitchSearch.plot_cumulative_max()`
- `MCMCSearch.plot_cumulative_max()` now no longer needs to re-initiate the search object to be on the safe side
- It still cannot be run before `.run()`, but I've also added an earlier explicit error message about that at the point where the old version would already have failed too.
- As discussed, this means SFTs are also checked and a catalog loaded _before_ reusing data from disk. But another check would have already failed if SFTs were deleted and only the results pickle file still kept, so this doesn't hurt in that case, and since it's only loading a catalog (not the full data, I think at least that's what it does) it should also not slow things down too much.
- Fixes …
> MCMC: initiate search object before checking for old data, plus cumulative fixes

- pyfstat/core.py
This specialised CFSv2 wrapper has been unused since #215. Contrary to its name, it actually was dedicated to getting "loudest" outputs. MCMCSearch has its own version in `generate_loudest()` of that which has been more recently maintained, and if there is a need to have an equivalent at the core level (e.g. so grid-based searches can also use it), it'd be better to promote that one.
> ComputeFstat: remove get_full_CFSv2_output()

- docs/source/conf.py
Order class members (and classes within a file) by order in the source .py file, instead of resorting alphabetically.
> sphinx: autodoc_member_order = "bysource"

- pyfstat/make_sfts.py
- It seems this wasn't actually doing anything,
probably because unlink doesn't understand * wildcards or something.
- It was contrary to the whole check-if-safe-to-reuse idea
the code actually uses.
@Rodrigo-Tenorio quick sanity check please
> Writer.run_makefakedata(): remove dysfunctional code for removing old files

- examples/grid_examples/PyFstat_example_grid_search_F0.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- tests.py
`BSGL` option to `GridSearch` was broken, giving a key error at some point. That alone would have been a two-line fix, but it's better to clean things up a bit more, changing our output log base following the decisions made ages ago for LALSuite:
- lnBSGL is the more natural quantity (analogous to F~lnBSG)
but log10BSGL as the output is consistent with lalapps choices
- also fixes issues with output format keys in GridSearch
- also removes a few superfluous explicit `BSGL=false` settings from examples to reduce clutter
> fix BSGL/lnBSGL chaos to consistent log10BSGL

- pyfstat/helper_functions.py
-  These were introduced in 975f1f5c4494036c3db3ec39fb4e0dfe6b9f8628
in the context of the `DMoff` classes which have been removed
due to being unmaintained.
> helper_functions: remove compute_P_twoFstarcheck() and compute_pstar()

- pyfstat/helper_functions.py
cc @GregoryAshton yet another orphaned function from the DMOff functionality. This one is easy to understand and wouldn't be much maintenance effort, but it's also completely isolated with all the other parts removed, so no real use in keeping it around.
> helper_functions: remove orphaned twoFDMoffThreshold()

- .gitignore
- README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/examples.rst
- docs/source/index.rst
- docs/source/modules.rst
- docs/source/pyfstat.rst
- docs/source/readme.rst
Uses [m2r2](https://pypi.org/project/m2r2/) to directly include the `README.md` into the sphinx html pages. Notes:
- most tutorials still recommend the original `m2r` but it seems to be abandoned
- md->rst involves conforming to rst's very picky standards, which include issuing warnings for multiple external links with the displayed text ("Duplicate explicit target name"). I didn't find a simple workaround, so I just modified the README to only use unique link texts.
- `readme.rst` doesn't have a heading on purpose, because that would lead to duplication in the TOC.
Also:
> Sphinx-Gallery will not manage its dependencies when installing
> Sphinx include readme

- requirements.txt
- setup.py
- tests.py
This was introduced in https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1428 and can now be used instead of the `lalapps` equivalent. We only used that one once in the tests, though.
Using the opportunity for a general lalsuite requirement version bump too, also to exercise our release and upgrade chain when it comes to those...
@Rodrigo-Tenorio main review question: am I overlooking any other place where versions are defined for conda/docker/...?
> bump to lalsuite>=6.80 and use lalpulsar.ValidateSFTFile()

- pyfstat/make_sfts.py
To resolve #156: I knew I had something more planned for using the new XLAL validation function than just the test case in #255.
Touching that final if block also made me realise there was some unnecessary messiness between handling joined or split SFT names, which the first commit here improves now.
> Writer: SFT files/path cleanup and add validatation call

- pyfstat/mcmc_based_searches.py
I messed up when I re-implemented the `injection_parameters` option
> Fix plot_prior_posterior when no injection parameters

- examples/binary_examples/PyFstat_example_binary_mcmc_vs_grid_comparison.py
- examples/grid_examples/PyFstat_example_grid_search_with_BSGL.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search_with_BSGL.py
- examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- pyfstat/tcw_fstat_map_funcs.py
- tests.py
Here's another big messy PR changing lots of internals, with the main goal to fix the BSGL implementation, but along the way cleaning up the way the likelihood and detection statistic functions are called and outputs are stored. It also adds some basic test cases and examples for BSGL usage in both grid and MCMC classes, resolving #99.
Some highlights from the commits:
---
- fixed basic twoFX and BSGL computation logic for transient and semicoherent cases, generalized to Ndet>2
- split up the various detection statistic methods into generic and specific ones
- introduce generic `_get_detstat_from_loglikelihood()`
- fix missing logic for BSGL case in various places
- for MCMC classes:
- clarify likelihood-detstat relation, `_set_likelihoodcoef()` now also takes care of twoF->F and of BSGL …
> BSGL readiness and internal cleanup

- pyfstat/helper_functions.py
- this was still done through helper_functions.set_up_matplotlib_defaults()
- instead, we should only rely on the optional import logic
based on whether "DISPLAY" is set in the env
- closes #268
Works for me on my laptop and on CIT. @Rodrigo-Tenorio any concerns this may be a problem in docker containers?
> do NOT always set matplotlib backend to agg

- requirements.txt
- setup.py
- see https://git.ligo.org/lscsoft/lalsuite/-/issues/414
- should hopefully fix #272
> pin numpy<1.20 to fix lalsuite incompatibility

- README.md
Hi, I'm doing the review for the JOSS submission about PyFstat (openjournals/joss-reviews#3000) and while following the installation instructions ran into a minor issue with the venv ephemerides installation snippet, it says to run `mkdir $VIRTUAL_ENV/share/lalpulsar` which can fail if `mkdir $VIRTUAL_ENV/share` does not exist with a `mkdir: cannot create directory` error.
This PR just adds a `-p` flag to the mkdir command so create any missing parent directories.
> Add parent flag to mkdir for venv ephemerides

- CHANGELOG.md
- pyfstat/make_sfts.py
- Checks in `_basic_setup` clash against different options in Artifact.
- Now it works.
> FrequencyModulatedArtifactWriter: Juggle input params to circumvent a parent check

- .github/workflows/integration.yml
Followup to #276 trying to avoid this situation:
- solution by dantup & johnbillion at https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
> avoid duplicate checks on internal PRs

- docs/source/modules.rst
- docs/source/tests.rst
@Rodrigo-Tenorio as discussed: [the generated page](https://pyfstat.readthedocs.io/en/v1.11.2/tests.html) isn't really useful anyway, and most other packages in the field don't seem to document their test suite on Readthedocs either.
> remove tests from compiled docs

- docs/requirements.txt
- dependabot bumped it from 8.1.0 to 8.1.1 in https://github.com/PyFstat/PyFstat/pull/292
- but next version is also a security fix: https://pillow.readthedocs.io/en/stable/releasenotes/8.1.2.html
> bump pillow to 8.1.2 in docs/

- .github/workflows/run_examples.yml
- should no longer need external gridcorner dependency now that we have an internal copy of it (introduced in #227 )
> run_examples.yml: remove external gridcorner dependency

- .readthedocs.yml
- docs/source/conf.py
For the actual readthedocs builds, this doesn't seem to be currently possible:
* https://github.com/readthedocs/readthedocs.org/issues/4529
But for PRs the extra banner is clear enough, "latest" is always "latest" by definition, and while it would be nice to say on "stable" which version it is, at least I can "activate" additional stable-stable tagged versions for posterity.
> sphinx: use pyfstat.__version__ at least on local builds

- pyfstat/mcmc_based_searches.py
I attempted to improve titles by using `g` format, but it's tricky.
This PR will close #184
> tweaks to corner plots

- tests.py
- we obviously don't test what's actually shown in the figures,
but just that the calls don't fail
- skipping MCMCTransientSearch for now
due to calculate_twoF_cumulative() failure
- refs #142
- let's see how bad runtime becomes and reduce to a few
test cases if needed
> tests: cover MCMC plotting methods

- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
- examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
- examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
- examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
- pyfstat/core.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
Followup to #315, fixes #316 and extends support for transients in CFS/PFS cumulative functions in general.
Notes:
1. Main change for non-transient applications is that the MCMC cumulative plots will now be saved to a file by default, overriding the behaviour of the core function but better matching all other MCMC plotting methods.
2. For `calculate_twoF_cumulative()` it may be cleaner to refactor it with some kwarg logic, but this will do for now.
3. The addition of a `transientWindowType` override parameter to `get_predict_fstat_parameters_from_dict()` is also a hack, and could have just done it on the level of the examples calling that function, but since it's just a "helper", I think this is fine for now.
> Fix cumulative plots for transients, extend examples and tests

- .zenodo.json
- stable "stable" link for now, so it doesn't need to be manually updated for each release
> .zenodo.json: add readthedocs as related_identifier

- README.md
Looks like the links were lost at some point during the overhaul.
> Restore reference to (pt)emcee

- setup.py
Since a month or two, LALSuite and numpy are supposed to be on speaking terms again. Let's see if this works.
> stop pinning numpy<1.20

- setup.py
Discovered this nice feature after seeing black's changelog link: https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
@Rodrigo-Tenorio any other important things to link?
> setup.py : add project_urls for PyPI sidebar

- Dockerfile
Python is dead, long live Python.
> Pump Python3.8 to Python3.9 in Docker container

- .github/workflows/integration.yml
- CHANGELOG.md
- README.md
- pyfstat/make_sfts.py
- setup.py
Fixes #340 by switching to the `lalapps_SplitSFTs` "NB" file name convention from https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1687 in `FrequencyModulatedArtifactWriter.concatenate_sft_files() and dropping python 3.6, which is no longer supported for recent LALSuite versions.
We'll want a 1.12.0 release with this.
> Update SFT NB file name convention, require python>=3.7 and lalsuite>=7.1

- pyfstat/mcmc_based_searches.py
- following https://matplotlib.org/3.1.0/api/api_changes.html#deprecation-of-redundant-tick-attributes
- closes #344 
Visual diff passes.
cc @Rodrigo-Tenorio but I'll auto-merge this
> MCMCSearch.plot_corner(): fix deprecation warning

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- tests.py
In testing #346 I noticed that the handling of single-detector F-stats (`twoFX`) didn't really make sense. It was impossible to get them without setting `BSGL`, and the corresponding function didn't fail cleanly if one tried anyway.
- add separate singleFstats option to all ComputeFstat classes
(core classes and grid-based searches; no MCMC classes seem to currently make use of these attributes)
- BSGL implies this
- but can also use it on its own
- always pre-initialise self.twoFX
but only set FSTATQ_2F_PER_DET
if self.singleFstats
- get_fullycoherent_single_IFO_twoFs()
now fails if not self.singleFstats
> add separate singleFstats option to all ComputeFstat classes

- pyfstat/make_sfts.py
- tests.py
Here's the reason for the current test to fail: ~Executables are different~
```
/home/rodrigo/opt/miniconda3/envs/pyfstat-conda/bin/lalapps_Makefakedata_v4 --outSingleSFT=TRUE --outSFTbname="TestData/H-4_H1_1800SFT_testing_cache-700000000-7200.sft" --IFO="H1" --ephemEarth="/home/rodrigo/gravity/venv/pyfstat/share/lalpulsar/earth00-40-DE405.dat.gz" --ephemSun="/home/rodrigo/gravity/venv/pyfstat/share/lalpulsar/sun00-40-DE405.dat.gz" --startTime=700000000 --duration=7200 --fmin=29.96404307059555 --Band=0.07191313888519033 --Tsft=1800 --window="tukey" --tukeyBeta=0.001 --h0=5 --cosi=0 --phi0=0 --Freq=30 --noiseSqrtSh=1 --lineFeature=TRUE --randSeed=42
lalapps_Makefakedata_v4 --lineFeature=TRUE --outSingleSFT=TRUE --outSFTbname="TestData/H-4_H1_1800SFT_testing_cache-700000000-7200.sft" …
```
> Fix line writer cache

- CHANGELOG.md
- pyfstat/make_sfts.py
- in FrequencyModulatedArtifactWriter.concatenate_sft_files()
- restores compatibility with pre https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1687
lalapps version
that was removed in https://github.com/PyFstat/PyFstat/pull/341
- refs #353
> add lalapps NB filename convention backwards compatibility

- pyfstat/core.py
- pyfstat/helper_functions.py
Addressing the first half of #356:
- deprecate `$LALPULSAR_DATADIR` solution
- fall back to standard `[earth/sun]00-40-DE405.dat.gz` file names
and relying on lal's path resolution
instead of "None"
- this should now work reliably on conda and pip installs
after https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1746
As long as not actually removing the `$LALPULSAR_DATADIR` hack from both the code and the actions setup, this step should be backwards-compatible for now.
> Simplify ephems handling part 1

- pyfstat/mcmc_based_searches.py
- following https://matplotlib.org/3.1.0/api/api_changes.html#deprecation-of-redundant-tick-attributes
- previously missed these lines in ba891805757cd3131acea3faffa1f822e94e7162
>  MCMCSearch.plot_corner(): fix deprecation warning v2

- examples/grid_examples/PyFstat_example_grid_search_F0.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1.py
- examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/mcmc_based_searches.py
- tests.py
- add generate_loudest() method to GridSearch via new helper function
- add helper_functions.generate_loudest_file()
- make GridSearch and MCMCSearch wrap that
- add to examples and tests
- improve grid examples
- report max point with injection offsets
- use inj dictionaries
- inject negative f1dot to be more typical
- call GridSearch with named parameters
> refactor generate_loudest() and add to GridSearch

- docs/source/pyfstat.rst
- pyfstat/__init__.py
- pyfstat/snr.py
- tests.py
(Must be merged after #378)
Implement a new module to compute SNRs using PyFstat. 
Incidentally, this also....
- Adds class to parse detectors states, which may come in handy for other methods.
- Allows to directly access the M matrix from PyFstat. 
To do:
Testing will consist in comparing against LALSuite's PFS via helper functions.
> Add Python API to compute SNR

- pyfstat/make_sfts.py
- tests.py
Allows to generate SFTs given a specific set of timestamps as a dictionary of numpy arrays, circumventing the creation of a timestamps file on the user side.
@dbkeitel after #379
> Improve timestamps support

- README.md
- setup.py
- tests/test_old_suite.py
- refs #264 (but doesn't resolve the underlying randomness)
Thanks to @mj-will for recommending [flaky](https://github.com/box/flaky)!
@Rodrigo-Tenorio please have a look. On top of standard filter trick recommended in the flaky README, I'm using a custom exception to only trigger the reruns in the specific places where we know there is non-determinism.
> retry MCMC quantile failures thrice via flaky

- .github/workflows/conda-test.yml
- etc/pyfstat-dev.yml
@dbkeitel 
Not sure if it's going to be a long term solution , but will do the trick for now if it works.
Edit: Falling back to the "install using pip" route, including a specific flag to avoid installing anything with pip.
> Ignore setup.py dependencies to test conda environment 

- pyfstat/snr.py
- tests/test_snr.py
Seems we missed this one @dbkeitel
> compute_snr2: Change phi0 to phi to be consistent with PyFstat

- .binder/postBuild
Following #395 & #397, let's make sure tutorials are accessible via Binder.
> Configure binder to deal with tutorial notebooks

- pyfstat/core.py
- pyfstat/tcw_fstat_map_funcs.py
The whole `tcw_fstat_map_funcs` module is ugly and I would code it differently nowadays, but it still seems to basically work, so this just makes the user interface less confusing by actually throwing an error if one, say, asks for `cuda` instead of `pycuda` - before it just silently fell back to the CPU lalpulsar implementation.
> init_transient_fstat_map_features: be strict about feature strings

- README.md
Reordered install methods, no longer giving an explicit conda command (better if people read the whole wiki page on that), moved ephems stuff to a wiki page too.
> README: reorganise install methods

- pyfstat/mcmc_based_searches.py
- setup.py
This first adds local copies of the ptemcee-1.0.0 autocorr functions (taken from [the PyPI release tarball](https://files.pythonhosted.org/packages/81/1d/2b3f09f0eb3ce8530e59b03e1aab4bc260cc14ddbc7dad761f9107d944e6/ptemcee-1.0.0.tar.gz)). Then it does a simple cast of lists of slices to tuples to fix the incompatibility. Numpy pin can now be removed.
Comparison run of `examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py` with PyFstat 1.15.0 from conda:
```
17:20 INFO    : Running final burn and prod with 400 steps
100%|███████████████████████████████████████████████████████████| 400/400 [00:06<00:00, 58.57it/s]
17:20 INFO    : Mean acceptance fraction: [0.131275 0.338375]
17:20 INFO    : Tswap acceptance fraction: [0.096075 0.096075] …
```
> fix ptemcee incompatibility with numpy 1.23.0 via local copies of autocorr functions

- pyfstat/make_sfts.py
- replaced with just "timestamps"
Was deprecated in 1.14.0. Since I keep finding myself using the old argument name in new code, better to kill it off for good...
> Writer: remove deprecated timestampsFiles option

- examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/__init__.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- pyfstat/tcw_fstat_map_funcs.py
- tests/test_core.py
- tests/test_grid_based_searches.py
- tests/test_mcmc_based_searches.py
- implemented in `ComputeFstat` and `TransientGridSearch` classes
- based on [XLALComputeTransientBstat](https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/group___transient_c_w__utils__h.html#gaf66cf2ffa017a6b1dffd266139b52fad) and Prix, Giampanis & Messenger 2011
- introduces a `ComputeFstat.get_transient_detstats()` method and makes `get_transient_detstats.get_transient_maxTwoFstat()` a legacy wrapper around it
- refs #260
Currently with `tCWFstatMapVersion="lal"`, the original lalpulsar function is called for BtSG as well. With `tCWFstatMapVersion="pycuda"`, the python version of BtSG is called after the pycuda computation of the FstatMap. A naive python port of that function (with double for loop) was very slow (BtSG took up to factor 10 longer than FstatMap), but a simple change to …
> implement transient BtSG statistic

- pyfstat/core.py
- pyfstat/helper_functions.py
- tests/test_helper_functions.py
See #417 - we actually only used the tool for a single logging output of SFT timestamps, so why not replace it with a pure python/swig solution. As a lal/datetime hybrid, I wouldn't bet though on it being as locale and leap-second robust as the executable solution (which does some custom stuff on a long and winding gps->utc->unix->utc road), so I slapped a notice on the helper function documentation not to trust it for anything beyond simple info output.
- also add test module,
since so far helper functions were all
just tested implicitly from via modules
> replace lalapps_tconvert with new helper function

- examples/transient_examples/PyFstat_example_short_transient_grid_search.py
- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/tcw_fstat_map_funcs.py
- tests/test_core.py
Changes in #413 , although very useful, introduce a completely different coding style depending on which arguments are being given into a function.
This PR solves that by substituting `weakref.finalize` by context managers.
Must be merged after #413
> fix pycuda detaching with weakref and contex manager

- setup.py
- try to work around isort incompatibility
while waiting for https://github.com/gforcada/flake8-isort/pull/116
> pin flake8<5.0

- pyfstat/grid_based_searches.py
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
- pyfstat/mcmc_based_searches.py
- pyfstat/snr.py
- tests/test_grid_based_searches.py
- tests/test_helper_functions.py
- tests/test_make_sfts.py
fixes #425 and makes progress on #417 by adding a transitional helper function `get_lal_exec()` for dynamically selecting `lalpulsar_` if available and falling back to `lalapps_` else.
> lalapps->lalpulsar migration with compatibility helper function

- pyfstat/mcmc_based_searches.py
First step towards #333 : Make sure there's no confusion and things are not wrongly used by mistake.
- closes #431
> Deprecate old MCMCFollowUpSearch and optimal setup functions

- etc/pyfstat-dev.yml
- pyfstat/helper_functions.py
- pyfstat/make_sfts.py
> finish lalapps->lalpulsar migration

- pyfstat/__init__.py
- pytest.ini
add pytest.ini to configure log level
- default will be to report >=WARNING for passing
and >=INFO for failing tests
- can still be overridden by e.g.
pytest --log-cli-level INFO
- no actual log_file set for now
Also added missing `f` to exception printing.
> Refurbish logging pytestconfig

- pyfstat/snr.py
- tests/test_snr.py
@Rodrigo-Tenorio exposes and fixes a missing list->np.array conversion in DetectorStates
For reference, error from running with the first commit only is
```
FAILED tests/test_snr.py::test_DetectorStates - AttributeError: 'list' object has no attribute 'ndim'
```
> DetectorStates ts nparray

- README.md
- etc/pyfstat-dev.yml
- etc/pyfstat.yml
- setup.py
- supersedes #442 
- pyfstat-dev.yml
- sort dependencies
- add missing attrs
- pyfstat.yml
- bump to python >= 3.8
- setup: skip lalsuite if NO_LALSUITE_FROM_PYPI set
- use this in pyfstat-dev.yml
to avoid duplicate packages from conda and pip
- plus some misc README updates
Wiki will be updated to match.
> Update recipes v2

- README.md
- etc/pyfstat-dev.yml
- setup.py
- no longer needed since #453
- also sort dependencies in README alphabetically
> Drop peakutils

- pyfstat/logging.py
- pyfstat/utils/cli.py
Python 3.7 is still partially alive (and more so in scientific contexts), so let's try to keep PyFstat 3.7 compliant even though Numpy itself is not anymore.
> Revert walrus operator

- README.md
No more dodgy tricks tweaking around environmental variables and going down to Python's guts: The obvious way actually works.
> Reformulate instructions to use lalsuite from source

- pyfstat/logging.py
Spotted a couple of minor typos in the logging docstring.
> Fix minor typos in logging docstring

- pyfstat/snr.py
- pyfstat/utils/__init__.py
- pyfstat/utils/converting.py
- tests/test_utils/test_converting.py
Extracts the existing one from an `snr` internal method to `utils.converting`, and adds the inverse, so they can be reused by other modules too.
Inverse should match https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/_compute_fstatistic__v2_8c_source.html#l02045
> add (h0,cosi)<->(aplus,across) functions to utils.converting

- docs/source/pyfstat.utils.rst
- pyfstat/core.py
- pyfstat/utils/__init__.py
- pyfstat/utils/atoms.py
- tests/test_utils/test_atoms.py
- fixes #488
- segfault discovered via `pytest tests/test_grid_based_searches.py::TestGridSearchBSGL::test_semicoherent_grid_search` with `lalsuite>=7.10.1.dev20221025`
- non-elegant solution for now: manual deepcopy of atoms data array
- timing impact seems to negligible
> fix segfault in get_semicoherent_single_IFO_twoFs() with recent lalsuite

- pyfstat/make_sfts.py
- tests/test_make_sfts.py
- check for missing `detectors` if `timestamps` are a string
- allow single-column timestamps files (and warn for Ncol>1)
> Writer timestamps handling improvements

- examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
- examples/tutorials/1_generating_signals.ipynb
- pyfstat/__init__.py
- pyfstat/injection_parameters.py
- pyfstat/make_sfts.py
- tests/test_injection_parameters.py
- tests/test_old_api_injection_parameters.py
Closes #485 
Things to do:
- ~Test that all these can be done from a TOML file with a proper syntax.~ Input is consistent with what the user can specify in a TOML file, so this is all god.
- ~Use structured arrays rather than dicts?~ Left for future implementation. Typing of outputs may be tricky.
> 485 refurbish injection parameters

- docs/source/conf.py
- setup.py
A feature I've been subconsciously missing for a long time, and only now found out there's a module for it.
The `rst_prolog` stuff in the config comes from [their "Usage" recommendation](https://github.com/zwang123/sphinx-autodoc-defaultargs/blob/e3e4a123380ca54b7052571d0b2ac2f27fed2af3/README.md#usage) and seems to be called a "substitution rule" in sphinx lingo.
> add sphinx_autodoc_defaultargs and update to sphinx 5.3.0

- tests/test_utils/test_cli.py
Previous version of the test case assumed that every single message would be INFO, which is generally not the case as exemplified in #498 .
This PR fixes that problem by comparing solely on `INFO` lines, which is the main test case of this test.
> test_cli.py/Only actually test that INFO messages match

- pyfstat/grid_based_searches.py
- tests/test_grid_based_searches.py
first commit: add test_transient_grid_search_notransient case
- expose attributes bug in TransientGridSearch if no actual transient parameters are set
- example failure: https://github.com/PyFstat/PyFstat/actions/runs/3518016425/jobs/5896456917
second commit will fix it
> fix attributes bug in TransientGridSearch if no actual transient parameters are set

- pyfstat/core.py
- tests/test_core.py
- match lalpulsar.write_MultiFstatAtoms_to_fp columns header line
- so that e.g. np.genfromtxt() and hence pyfstat.utils.read_txt_file_with_header() work on these files without getting confused by inconsistent comments markers
@itsluanayall did you never run into that problem (numpy.genfromtxt complaining about inconsistent line lengths because it doesn't understand our own header lines having `#` and the one from lalpulsar having `%%`? Or asked the other way round, any scripts of yours that this change would break?
> write_atoms_to_file: change header comments to %%

- etc/pyfstat-dev.yml
- setup.py
Lalsuite 7.11 (including lalpulsar 5.2.0) came out today, and we'll likely put in at least one feature before our next release requiring functions added in that release. Next, we expect the backwards-incompatible release (with bump to lalpulsar 6.0.0 and probably (but not sure) to lalsuite 8.0) which we do _not_ want to have our CI or users pull in as upgrades automatically, so we want to pin <= that. (see #481)
We could try `lalsuite>=7.11,<8.0` but since we're not entirely sure of the next version's number, we can just go with `==7.11` for now and, if another backwards-compatible release happens first, rebump in a minor release from our side.
Conda to be done separately, as usual.
> pin lalsuite==7.11

- pyfstat/make_sfts.py
I just correct a minor typo `antenna-patern` to `antenna-pattern` in `LineWriter` docstring!
> Fix minor typo in `LineWriter` docstring

- .github/workflows/conda-test.yml
This seems to fix #519: -> https://github.com/PyFstat/PyFstat/actions/runs/4046072271/jobs/6958397252 :heavy_check_mark: 
Since mamba is marked as experimental, I guess just skipping it for now when there's an incomprehensible error is the easiest way out. Any objections @Rodrigo-Tenorio ?
> try conda-test without mamba

- pyfstat/core.py
Oops, beginner's indexing mistake in the `pprint_init_params_dict() function`. @itsluanayall spotted this as TransientGridSearch randomly not outputting the window type parameter; turns out always the 2nd-to-last param wasn't printed, because I can't index.
> Fix params dict in output file headers

- pyfstat/pyCUDAkernels/cudaTransientFstatExpWindow.cu
- pyfstat/pyCUDAkernels/cudaTransientFstatRectWindow.cu
- pyfstat/tcw_fstat_map_funcs.py
- tests/test_tcw_fstat_map_funcs.py
This adds the same antenna pattern matrix condition number check as in LALComputeAntennaPatternSqrtDeterminant() and estimateAntennaPatternConditionNumber(),  see https://git.ligo.org/CW/software/lalsuite/-/issues/13 and https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/122/  for the original LALSuite discussion. For now it's hardcoded to lalpulsar's standard 1e4 threshold and a fallback of 2F=4. It improves consistency between lalpulsar and pycuda results in rare corner cases, particularly when a transient window includes very few SFTs (typically 2) from a single detector, and even then it would only produce noticeable outliers for relatively rare Doppler parameter combinations.
While I revisited these files for the first time in years, I also added a basic test case that synths …
> PyCuda transient-Fstat kernels: add fallback for ill-conditioned antenna pattern matrix, and unit test

- examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
- examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
- examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search_with_BSGL.py
- examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
- examples/other_examples/PyFstat_example_twoF_cumulative.py
- pyfstat/make_sfts.py
- pyfstat/utils/__init__.py
- pyfstat/utils/predict.py
- pyfstat/utils/runlalsuite.py
- tests/test_grid_based_searches.py
- tests/test_make_sfts.py
- lalapps->lalpulsar migration is long over, so simplify away this transition helper
- closes #524
- also, in examples: remove outdated lalapps references in comments
> remove utils.get_lal_exec()

- examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
- pyfstat/mcmc_based_searches.py
- fixes #532
- This format seems to have been already supported by corner <2.2.2 as well, so no need to introduce a dependency pin.
- Now gives us 3 dashed lines, the extra one at median:
> corner 2.2.2 requires length-3 list for quantiles

- .github/workflows/test_lalsuite_dev.yml
- README.md
- setup.py
- closes #536
- LALSuite-dev test run: https://github.com/PyFstat/PyFstat/actions/runs/5112834724 (using `pip install --pre` for nightly lalsuite)
> use lalsuite[lalpulsar] to pull in solar-system-ephemerides

- .github/workflows/integration.yml
- follows new https://docs.pypi.org/trusted-publishers/ model
- split into separate jobs build, testpypi-publish, pypi-publish
- use environments
- use artifact upload/download
> adapt integration.yml to using OIDC for PyPI

- CHANGELOG.md
- README.md
- etc/pyfstat-dev.yml
- etc/pyfstat.yml
- setup.py
There's a versioneer-ConfigParser incompatibility (see https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/802015/logs/7 ), which is probably easy to fix, but LALSuite hasn't been updated yet anyway (https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/2201), so pin for now and check on it later.
> pin python<3.12 for now

- .github/workflows/flake8.yml
- .github/workflows/integration.yml
Continue making actions less monolithic. In this case, still install project as normal, since this allows using the same plugins and versions as defined in setup.py, even if it might be a bit overkill for linting only.
> add standalone flake8 action

- .binder/postBuild
- from sphx_glr_python_to_jupyter which seems to no longer exist (in sphinx-gallery 0.16) with similar-sounding sphinx_gallery_py2jupyter
- closes #538
> update sphinx executable in binder postBuild

- pyfstat/utils/predict.py
- allow passing dicts following either the lalpulsar or PyFstat convention and always return in lalpulsar convention
- this helps e.g. when passing the same dicts to `Writer`-type objecs and to this functions.
> get_predict_fstat_parameters_from_dict(): deal with both naming conventions for transient params

- pyfstat/core.py
- pyfstat/grid_based_searches.py
- pyfstat/mcmc_based_searches.py
- tests/test_core.py
- tests/test_grid_based_searches.py
- tests/test_mcmc_based_searches.py
Some 2-year old edits I had lying around locally, rebased onto current master. This is a prerequisite for improvements such as #335.
`get_fullycoherent_detstat` and friends now take an optional `params` dictionary argument that can replace the old-style individual arguments for F0,... and the old style is already labeled as DEPRECATED and might be removed in the future. This will allow for including higher spindowns and non-standard parameters.
Along the way, I've also centralised the internal defaults for LaTeX labels into the core class.
> Allow core F-stat functions to take a dict for parameters

- examples/tutorials/tutorial_utils.py
Plotting amplitude and phase function was not working with the newest version of madplotlib.
Solved by using pcolormesh.
Fixes #572
> Change in tutorial_utils.py spectogram plotting funcion.

- pyfstat/grid_based_searches.py
- tests/test_grid_based_searches.py
Fixes the missing `BtSG` support in `SearchOverGridFile` and improves logging.
> Gridsearch BtSG support and logging

- .github/workflows/integration.yml
- we need setuptools>=69.3.0 to support PEP 625
- to avoid PyPI deprecation warnings about sdist filename
> upgrade setuptools in integration.yml

- CHANGELOG.md
- README.md
- etc/pyfstat-dev.yml
- setup.py
I think the pin only remained in place after https://github.com/PyFstat/PyFstat/commit/6571123804f821c6a61d2bdd07607a8e06f80936 because of lalsuite (or maybe some other) dependencies, and since those seem to have all fixed their compatibility, I'm not getting any test failures unpinning.
> unpin numpy (allow >=2)
