PyFstat/PyFstat

pyfstat/core.py
tests.py

@GregoryAshton Trying to test #11 I ran into this "not implemented" case, seemed simple enough to fix.
-allow running a search on pure Gaussian noise
without making SFTs first
-adding a test case for this
-also storing more parameters in Test base class,
will be re-used more thoroughly in a future MR

implement CFS feature injectSqrtSX

---

pyfstat/make_sfts.py

-fixes #8
@ReinhardPrix is this sufficient for the problem you were seeing?

Writer.predict_Fstat(): place temporary output file in self.outdir

---

examples/grid_examples/grid_search_F0.py
examples/grid_examples/grid_search_F0F1.py
examples/transient_examples/short_transient_search_gridded.py
pyfstat/core.py
pyfstat/grid_based_searches.py
pyfstat/helper_functions.py
setup.py

refs #7 (but doesn't close it, as MCMC not yet addressed)

improve grid search output file headers

---

examples/glitch_examples/make_simulated_data.py
examples/glitch_examples/semicoherent_glitch_robust_directed_MCMC_search_on_1_glitch.py
examples/glitch_examples/semicoherent_glitch_robust_directed_grid_search_on_1_glitch.py
examples/glitch_examples/standard_directed_MCMC_search_on_1_glitch.py

-closes #20 
Removes custom matplotlib style, and fixes file paths to match other examples.
But there's a plotting bug I'm now encountering, will report separately.

fix glitch examples

---

pyfstat/mcmc_based_searches.py

MCMC: open pickle files in binary mode
Guess this is a python 3 thing.
-fixes #19
-fixes #21

tastier dill pickles with some binary spice

---

pyfstat/make_sfts.py
tests.py

Ref. #40 
P. S.
@dbkeitel I'm not sure if this is the right way to do this: This builds upon #39. After getting #39 merged into master, I'll properly rebase this one on top of master from the point of divergence.

implement noiseSFTs option for Writer

---

examples/other_examples/test_noise_sfts.py

Reverted this for testing the pipeline failures, now put it back in.

re-add test_noise_sfts.py from before 7bf818d0

---

pyfstat/helper_functions.py
pyfstat/make_sfts.py
setup.py

- [lalsuite-6.72](https://pypi.org/project/lalsuite/6.72/) has been released on pypi and should solve our scary-looking problems with 6.71 (#52)
- see https://git.ligo.org/lscsoft/lalsuite/-/issues/340 and https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1369 for the underlying problem and fix
- first commit reverts commit 2380a6c4bd84660c7daa8dc2194ce3460faa2162 (from #56)
- additional test errors resolved in further commits

lalsuite-6.72 compatibility

---

examples/glitch_examples/semicoherent_glitch_robust_directed_MCMC_search_on_1_glitch.py
examples/grid_examples/grid_search_F0F1.py
examples/grid_examples/grid_search_F0F1F2.py
pyfstat/mcmc_based_searches.py

two more issues fixed:
1. confusing labels of grid searches
1. glitch search incompatible with loudest CFSv2 call

Fix examples

---

pyfstat/helper_functions.py
pyfstat/make_sfts.py

Here's a much cleaner solution to #60.

Writer.check_cached_data_okay_to_use(): clean solution to cmd from SFT

---

Dockerfile

Solve #74 including steps to download ephemerides during docker build.

Add Ephemerides to Dockerfile

---

pyfstat/optimal_setup_functions.py

Improve documentation for optimal setup

---

README.md
setup.py

@Rodrigo-Tenorio congratulations, I think your contributions have already been sufficient to add you to the author list in the bibtex citation. Thanks a lot for everything so far!
Do you have an ORCID? If yes, please note it here and then we (Greg) can enter that in the next Zenodo release.
@GregoryAshton @ReinhardPrix any objections?

add Rodrigo to authors in bibtex (and later Zenodo)

---

pyfstat/make_sfts.py

- If noiseSFTs is given, one should count (i.e. use the catalog)
the actual number of SFTs, since data does not have to be continuous
in time.

[fix] make_sfts.py/Get the right number of SFTs

---

.github/workflows/integration.yml

1. put black before pytest
1. (still to do): try automated sdist/wheels builds and maybe even PyPi upload

integration.yml: put black first, build distributions, upload releases to TestPyPi

---

CHANGELOG.md
pyfstat/grid_based_searches.py
tests.py

Various small fixes and tests covering them.

GridSearch and TransientGridSearch: extend test coverage and fix small things

---

examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
examples/mcmc_examples/PyFstat_example_fully_coherent_MCMC_search.py
examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py

I didn't even know of that function until I broke it in another PR. ;) Seems quite nice!

add prior_posterior plots to MCMC examples

---

examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
pyfstat/core.py
pyfstat/make_sfts.py
tests.py

This will partially address #90 but further PRs will be required. See commit messages and comments below for details.

make_sfts: change options to better distinguish signal duration vs data duration

---

pyfstat/mcmc_based_searches.py

- Somebody made a silly mistake when changeing variable names!
- Also improve cumulative `or`.

[hotfix/mcmc_based_searches.py] Fix variable name

---

pyfstat/grid_based_searches.py

Wrong file pointer name. Looks almost like this is all that's needed to get the GPU version working again... fingers crossed...

fix typo in TransientGridSearch.write_F_mn()

---

pyfstat/mcmc_based_searches.py

Also introduces a _get_twoF_from_loglikelihood() helper method so the slightly arcane method of getting 2F values back from the log-likelihood doesn't need to be rewritten multiple times.

MCMC: save twoF into ASCII .dat output file

---

README.md

I changed the other DOI down there in the README to be consistent with the DOI badge at the top of the file.

Quote consistent DOIs

---

pyfstat/mcmc_based_searches.py

- new method get_summary_stats() for mean, std, quantiles
- get_median_stds() deprecated, will be removed later
The old "median+-std" isn't really a common or very meaningful choice.
This only really impacts the `print_summary()` text output and hence should be rather safe;  `write_par` is also updated to allow mean in addition to median as an option, but no changes to default behaviour.
It'll merge this before trying to address #112 , regardless of tests state. The only failure I saw locally was one of those tolerances again.

MCMC: report mean+-std and/or median+-90% instead of median+-std

---

pyfstat/mcmc_based_searches.py
tests.py

resolves #112 (I hope)
Still cannot be **guaranteed** to always succeed, but should be much more reliable than fixed tolerances.
If it fails again more often than I'd hope, we can try fixing "nice" random seeds.

MCMC tests: check if inj params within mean+-2std and within 90%

---

pyfstat/core.py

To be applied after #125. Does not appear to need any additional test suite fixes. :)
various fixes/cleanups of SemiCoherentSearch
-consistently use maxStartTime both for SFT reading constraints
and for segment setup, should be consistent with LAL conventions
-clearer logging and error messages on user input checking and
data readin
-make Tsft an option of ComputeFstat and derived classes
and don't re-set it multiple times
-clean up when/where windows and atoms choices are made
-added in-code comments to justify some choices

Semicoherent cleanup

---

examples/glitch_examples/PyFstat_example_make_data_for_search_on_1_glitch.py
examples/grid_examples/PyFstat_example_grid_search_F0.py
examples/grid_examples/PyFstat_example_grid_search_F0F1.py
examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
examples/mcmc_vs_grid_simple_example/PyFstat_example_make_data_for_simple_mcmc_vs_grid.py
examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py
examples/other_examples/PyFstat_example_sliding_window.py
examples/other_examples/PyFstat_example_twoF_cumulative.py
examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py

@Rodrigo-Tenorio  my part of fixing #123

add missing defaults to more examples

---

examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_search.py
pyfstat/mcmc_based_searches.py

-added kwarg to one example to verify
-closes #104
As approved by Greg over on the issue.

MCMCSearch._plot_walkers(): fix F->2F

---

.github/workflows/integration.yml

Black (literally) just released a new version. 
We (@dbkeitel ) decided to pin this repo's version to the old one until current PRs are done.

Pin Black version to 19.10b0

---

pyfstat/mcmc_based_searches.py

Hot fix some options for a single inference I did not properly test .

Fix plot_prior_posterior for a single inference

---

.github/workflows/run_examples.yml
examples/run_all_examples.py

- manual workflow to run all examples, e.g. before making a release

create action to run all examples

---

pyfstat/make_sfts.py
tests.py

Implement #144 and probably further simplify writer classes

Make simpler parameter parsing method

---

examples/binary_examples/PyFstat_example_semi_coherent_binary_search_using_MCMC.py
pyfstat/make_sfts.py

Implement the argument-independent first introduced in #39 as part of BinaryModulatedWriter into Writer.

Refactor Writer class

---

pyfstat/mcmc_based_searches.py

- allows to remove redundant arguments from various methods
- also introduce a new MCMCFollowUpSearch._get_p0_per_stage() helper method making use of it,   which along the way will avoid F821 when we enable flake8 (#153)
@Rodrigo-Tenorio we'll need to merge this one first, does it look safe?

MCMC: store sampler as self.sampler

---

.github/workflows/run_examples.yml

Extend #147 by saving the output as artifacts (#149 )

Add artifact upload

---

pyfstat/mcmc_based_searches.py

Solve #164, although the initial discussion is in #172 by a silly mistake.

fix MCMCSearch.plot_prior_posterior()

---

.github/workflows/run_examples.yml
README.md
examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
pyfstat/mcmc_based_searches.py

Fix and update chainconsumer functionalities 

---

pyfstat/mcmc_based_searches.py

If any of the parameters is missing, ignore.

MCMC: Fix checks when plotting injection parameters

---

pyfstat/core.py
pyfstat/helper_functions.py
pyfstat/make_sfts.py
tests.py

Implement suggestions in #194 
(To be merged after #186 )

consistent parameter naming convention

---

examples/other_examples/PyFstat_example_InjectionParametersGenerator.py

- demonstrate both classes
- draw once, make SFTs
- draw 1000 times, plot sky distribution

add new example for InjectionParametersGenerator and its all-sky child

---

docs/source/conf.py
pyfstat/core.py

First round of improving documentation: fixing markup errors, extending class-level explanations, adding missing docstrings / parameter explanations, etc. Just did core.py so far.

Improve core docs

---

pyfstat/make_sfts.py

Next batch of proper documentation. For `FrequencyModulatedArtifactWriter` I had to guess a bit...

improve documentation of everything in make_sfts.py

---

pyfstat/grid_based_searches.py

Also changed `GridSearch.plot_2D()` argument `save` to `savefig` for consistency with other plotting methods.

Improve grid docs, make some methods private

---

pyfstat/helper_functions.py

helper functions: improve documentation and a few minor fixes

---

pyfstat/core.py

Safer that way, if the previously assumed defaults of 7 and 10 ever change, also easier to read.

core: use lalpulsar PULSAR_MAX_SPINS and PULSAR_MAX_DETECTORS macros

---

README.md
docs/source/pyfstat.rst
examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
examples/grid_examples/PyFstat_example_grid_search_F0F1.py
examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
pyfstat/__init__.py
pyfstat/gridcorner.py

taken from https://gitlab.aei.uni-hannover.de/GregAshton/gridcorner with @GregoryAshton's permission
- based on code from https://github.com/dfm/corner.py
- closes #225
@GregoryAshton do you think this is the right way to include the corner.py copyright licence? (Edit: full-text paste in the top-level docstring of the gridcorner.py file.) It seems compatible with our MIT licence, but probably safer to copy it over explicitly like this, right?

add gridcorner code 

---

.gitignore
examples/other_examples/PyFstat_example_injecting_into_noise_sfts.py

This one slipped under our radars

doc fixes: title undersocre too short error, .gitignore

---

.github/workflows/joss-pdf.yml

Add GitHub action to build JOSS paper

---

pyfstat/helper_functions.py

- resolves #157
- removes workarounds for insufficient checks on lalapps side
which have been fixed in https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1430

PredictFstat: simplify input checking

---

pyfstat/mcmc_based_searches.py

Minor refactoring of some proposals from #245 .

Refactoring bsgl

---

pyfstat/mcmc_based_searches.py

[docs mcmc_based_searches.py] Add prior documentation

---

pyfstat/mcmc_based_searches.py

Partially adressing #184 .
It's not the best solution, but does the trick and took me way less than I expected, so let's rejoice I say.

Change plot_corner defaults

---

tests.py

- signal and line need to be separated well enough in freq

fix TestMCMCSearchBSGL.test_MCMC_search_on_data_with_line

---

.github/workflows/integration.yml

Let's see if this resolves infinite ` Expected — Waiting for status to be reported ` when submitting from a fork...?

integration.yml: also trigger on pull_request

---

README.md

Update citation requests in the README to cover recent arXiv posting https://arxiv.org/abs/2101.10915 for under-review JOSS paper.
Also to test if automated tests work again on PRs, and from forks.

update citation requests in README

---

CHANGELOG.md
pyfstat/make_sfts.py
tests.py

@Rodrigo-Tenorio followup to #277
- needed to adapt concatenate_sft_files()
method to changed lalapps_splitSFTs filename convention

fix and test FrequencyModulatedArtifactWriter

---

docs/requirements.txt
pyfstat/__init__.py
pyfstat/make_sfts.py
tests.py

Implement a proper class to inject (possibly transient) lines in data using Makefakedata_v4.

Implement line writer

---

.github/workflows/integration.yml

- released Oct 15, let's try to be early adopters...
- ...and see just how much can go wrong ;)

add python 3.9 to integration.yml

---

README.md
codemeta.json

add codemeta.json and ASCL badge

---

.github/workflows/codecov.yml

- as suggest by @RobertRosca in #290

codecov.yml: only run on pyfstat package dir

---

MANIFEST.in

- hope this fixes conda-forge build #298

add requirements.txt and tests.py to MANIFEST.in

---

pyfstat/grid_based_searches.py
pyfstat/mcmc_based_searches.py

Simplify if-mkdir block to makedirs-exist_ok

---

pyfstat/core.py

Add return statement to get_semicoherent_twoF()

---

pyfstat/mcmc_based_searches.py

Label, symbol and unit can be None independently

---

tests.py

This should improve coverage a little bit.

TestComputeFstat: cover predict_twoF_cumulative()

---

tests.py

More test coverage.
- refs #142

TestGridSearch: basic plots coverage

---

examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
pyfstat/core.py
pyfstat/gridcorner.py
pyfstat/mcmc_based_searches.py

make black 21.4b2 happy: no extra whitespace in one-line docstrings

---

pyfstat/core.py
pyfstat/mcmc_based_searches.py
tests.py

Ad interface to modify the maximum-allowed mismatch by CFSv2

Add max mismatch

---

.github/workflows/test_lalsuite_dev.yml

test_lalsuite_dev.yml : use pip install --upgrade --pre

---

.github/workflows/conda-test.yml
etc/pyfstat-dev.yml

- `.github/pyfstat-test.yml` file with dependencies from https://github.com/conda-forge/pyfstat-feedstock/blob/476552529d2464cfde5f88de3e2dd9c0d490764e/recipe/meta.yaml
- action from https://github.com/marketplace/actions/setup-miniconda

set up conda test

---

.github/workflows/conda-test.yml
.github/workflows/integration.yml

We haven't gotten any angry e-mails from github ever, so: nightly integration test and weekly conda test for now.

increase test frequency

---

pyfstat/make_sfts.py
tests.py

fixes #327 but will need MFDv5 follow-up bug report for the actual signal-injection-into-narrowband-SFTs case

Fix expected SFT names for narrowband (freq-segmented) noiseSFTS

---

.pre-commit-config.yaml
examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
examples/glitch_examples/PyFstat_example_standard_directed_MCMC_search_on_1_glitch.py
examples/grid_examples/PyFstat_example_grid_search_F0.py
examples/grid_examples/PyFstat_example_grid_search_F0F1.py
examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
examples/other_examples/PyFstat_example_spectrogram.py
pyfstat/core.py
pyfstat/grid_based_searches.py
pyfstat/helper_functions.py
pyfstat/mcmc_based_searches.py
pyfstat/tcw_fstat_map_funcs.py
tests.py

Fixes #369. Mostly it now wants less spaces around powers.
However I also had to update the pre-commit config, without that I was in a strange loop where `black .` would reformat things, but then `git commit` would reset them. I guess that's somehow related with black now officially not being beta anymore, though I don't really understand why that means the generic `stable` is no longer ok... any thoughts @Rodrigo-Tenorio ?

Make black 22.1.0 happy

---

examples/other_examples/PyFstat_example_spectrogram.py
pyfstat/helper_functions.py
tests.py

This new function supports mulit-IFO and returns complex amplitudes rather than absolute values.

Improve SFT to Numpy array conversion

---

.github/workflows/codecov.yml

update codecov action to v2

---

examples/other_examples/PyFstat_example_spectrogram.py

Hotfix deprecation warning in PyFstat_example_spectrogram.py

---

examples/other_examples/PyFstat_example_spectrogram.py

PyFstat_example_spectrogram.py : remove grid

---

Dockerfile
README.md
pyfstat/core.py
pyfstat/helper_functions.py

- closes #356
@Rodrigo-Tenorio please check the Docker file especially.

remove deprecated $LALPULSAR_DATADIR use for ephemerides

---

.github/workflows/docker-publish.yml

Add manal trigger to docker action

---

pyfstat/make_sfts.py
tests/test_make_sfts.py

This should have been called out by a test?

Fix up a syntax error

---

setup.py

- temporary workaround
- refs #403

pin numpy<1.23.0 to avoid ptemcee index errors

---

pyfstat/snr.py
tests/test_snr.py

@dbkeitel should be straightforward.

Add new method to convert h0 and snr

---

pyfstat/tcw_fstat_map_funcs.py

- re, im should be enough
and complex can always be reconstructed
@itsluanayall this should make some things easier on your project. As "review" here I just need a second pair of eyes to check the changed loops make sense; I ran the relevant built-in test in GPU-enabled mode on Artemisa (for reference: `gpurun pytest tests/test_core.py -s --verbose -k finalizer`) and one on your project, so if the automated pipeline here also passes, in principle nothing should be broken.

reshape_FstatAtomsVector: don't store complex Fa, Fb

---

README.md

Add extra method to use lalsuite compiled from source

---

pyfstat/snr.py
tests/test_snr.py

Closes #427 
Add minimal tests for `DetectorStates` to make sure that
1. Different inputs actually work.
2. Different inputs are consistent amongst each other.

Hotfix timestamps snr

---

pyfstat/grid_based_searches.py
pyfstat/helper_functions.py
pyfstat/make_sfts.py
pyfstat/mcmc_based_searches.py

Remove unused, add as method/class attributes the ones on use.

Refurbish argparse options

---

.pre-commit-config.yaml
setup.py

Reverts PyFstat/PyFstat#424
Let's see if the isort incompatibility has resolved itself.

Revert "pin flake8<5.0"

---

.github/workflows/integration.yml
.github/workflows/test_lalsuite_dev.yml
CHANGELOG.md
README.md
etc/pyfstat-dev.yml
setup.py

- LALSuite as of 7.6 no longer supports it

drop python 3.7

---

pyfstat/grid_based_searches.py
pyfstat/make_sfts.py
pyfstat/mcmc_based_searches.py

Closes #449 , as `tqdm` seems to always go on its own towards stdout.

Remove tqdm redirection functions

---

pyfstat/helper_functions.py
tests/test_helper_functions.py

To be merged after #435 .
Closes #444.

444 modernize `run_commandline` logging

---

pyfstat/utils/sft.py
tests/test_utils/test_sft.py

Just checking that the output has the proper shape and deterministic data.

Add basic integrity check to get_sft_as_arrays

---

examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
pyfstat/mcmc_based_searches.py

- Vestige from the previous logging implementation
- Fixes #456

Remove empty logger calls

---

examples/glitch_examples/PyFstat_example_glitch_robust_directed_MCMC_search_on_1_glitch.py
examples/glitch_examples/PyFstat_example_glitch_robust_directed_grid_search_on_1_glitch.py
examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py

clean up some logging string formatting in examples

---

pyfstat/core.py
tests/test_core.py

closes #461
Any possible side effects?

fix finalizer for non-cuda case

---

.github/workflows/check_notebooks.yml
.github/workflows/integration.yml
examples/tutorials/0_generating_noise.ipynb
examples/tutorials/1_generating_signals.ipynb
setup.py

Testing the correctness of a tutorial is quite an involved task, so for now I'll implement a basic action item to make sure the notebooks run properly without exceptions.
Closes #467

Add CI action to run Notebooks

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

- feature request: based on github's suggestion, but made less coercive and less formal
- question: made up from scratch

add more issue templates

---

pyfstat/make_sfts.py
pyfstat/utils/__init__.py
pyfstat/utils/sft.py

- to make SFTspec v3 migration easier later on
- refs #481

add wrapper for lalpulsar.OfficialSFTFilename

---

pyfstat/injection_parameters.py
pyfstat/logging.py
pyfstat/utils/atoms.py
pyfstat/utils/cli.py
pyfstat/utils/sft.py

Closes #490 
Also, update and correct some minor typos in annotations.

Duplicate typing at output

---

CHANGELOG.md

update changelog for 1.19.0

---

examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
examples/tutorials/1_generating_signals.ipynb
pyfstat/__init__.py
pyfstat/injection_parameters.py

isotropic_amplitude_priors is not global anymore

---

pyfstat/tcw_fstat_map_funcs.py

Lesson recently learned: why would one ever not want to know which GPU one was running on...

init_transient_fstat_map_features: upgrade cuda/device info from DEBUG to INFO

---

.pre-commit-config.yaml
examples/mcmc_vs_grid_simple_example/PyFstat_example_simple_mcmc_vs_grid_comparison.py
examples/transient_examples/PyFstat_example_make_data_for_long_transient_search.py
examples/transient_examples/PyFstat_example_make_data_for_short_transient_search.py
examples/transient_examples/PyFstat_example_short_transient_MCMC_search.py
examples/transient_examples/PyFstat_example_short_transient_grid_search.py
pyfstat/injection_parameters.py
pyfstat/logging.py
pyfstat/make_sfts.py
pyfstat/mcmc_based_searches.py
pyfstat/snr.py
pyfstat/utils/importing.py
pyfstat/utils/sft.py
tests/test_core.py
tests/test_injection_parameters.py
tests/test_logging.py
tests/test_make_sfts.py
tests/test_mcmc_based_searches.py
tests/test_old_api_injection_parameters.py
tests/test_snr.py
tests/test_utils/test_atoms.py
tests/test_utils/test_converting.py
tests/test_utils/test_importing.py
tests/test_utils/test_sft.py

Black 23.1.0 was [released today](https://pypi.org/project/black/23.1.0/) and has gained new opinions, apparently mostly against empty lines. 
This should hopefully fix today's failures on master.

make black 23.1.0 happy

---

CHANGELOG.md
README.md

Readme and changelog. Helpful enough for non-experts?

metadata updates for v2.0.0

---

pyfstat/core.py
pyfstat/gridcorner.py
pyfstat/logging.py
pyfstat/mcmc_based_searches.py
pyfstat/optimal_setup_functions.py
pyfstat/utils/formatting.py

- make flake8-1.7.0 happy
- fixes https://github.com/PyFstat/PyFstat/issues/539
@Rodrigo-Tenorio for human review

change type checks to isinstance

---

.pre-commit-config.yaml
examples/followup_examples/PyFstat_example_semi_coherent_directed_follow_up.py
examples/grid_examples/PyFstat_example_grid_search_F0.py
examples/grid_examples/PyFstat_example_grid_search_F0F1.py
examples/grid_examples/PyFstat_example_grid_search_F0F1F2.py
examples/mcmc_examples/PyFstat_example_MCMC_search_using_initialisation.py
examples/mcmc_examples/PyFstat_example_semi_coherent_MCMC_search.py
examples/other_examples/PyFstat_example_InjectionParametersGenerator.py
examples/other_examples/PyFstat_example_twoF_cumulative.py
examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
pyfstat/core.py
pyfstat/grid_based_searches.py
pyfstat/injection_parameters.py
pyfstat/make_sfts.py
pyfstat/mcmc_based_searches.py
pyfstat/optimal_setup_functions.py
tests/test_make_sfts.py

Set it as the version of reference for pre-commit, and make it happy with minor 2024 style changes.

Black 24.4.2

---

.github/workflows/black.yml
.github/workflows/integration.yml

following https://black.readthedocs.io/en/stable/integrations/github_actions.html

add standalone black action

---

examples/other_examples/PyFstat_example_twoF_cumulative.py

- increasing depth accordingly

make cumulative 2F example 10 days instead of 100 for speedup

---

pyfstat/mcmc_based_searches.py

- early return needed in case of caught exception
- also make internal variable names consistent across init / main run

fix the fig,ax return case for MCMCSearch plotting methods

---

setup.py

- see https://github.com/PyFstat/PyFstat/issues/562

pin chainconsumer<1.0

---

pyfstat/__init__.py
pyfstat/core.py
pyfstat/grid_based_searches.py
pyfstat/make_sfts.py
pyfstat/mcmc_based_searches.py
pyfstat/utils/formatting.py
pyfstat/utils/runlalsuite.py
setup.py
tests/test_grid_based_searches.py

- Adds SearchOverGridFile class to read and use a grid from CFSv2
- Generalizes all code to deal with higher spindowns
- Adds pandas to dependencies for faster reading larger files

Search over grid file

---

pyfstat/grid_based_searches.py
pyfstat/tcw_fstat_map_funcs.py
tests/test_grid_based_searches.py
tests/test_tcw_fstat_map_funcs.py

If BtSG is set to True, t0_MP and tau_MP are also returned in the 
Consistent with `XLALFindModeOfPDF1D()`, we return the center-value of the discrete ' containing the maximum of the distribution.

Implementation of t0_MP and tau_MP computation for transient searches
